/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:8981831a-e3f9-48da-96a6-7ea6cc7450c2",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_yOS6kZz88",
    "aws_user_pools_web_client_id": "p70g3r4l9tpqvmt0k5p2mhqqn",
    "oauth": {
        "domain": "rnamplifycd59f72c-cd59f72c-dev.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
